### ISSUE TITLE
Use Fan L+R modes

### ISSUE THREAD

**Issue by keesvw** [absalom-muc/MHI-AC-Ctrl#109] opened 2022-11-04 14:26 UTC
Dear,
I am new to This Git and first appreciate all for the efforts done and give this project so much support.
Recently I build and implementen my first DIY controller in my MHI SRK50ZS-W / SCC50ZS-W split airco unit.
Initially I used the WF-RAC + Android app and noticed that in this app also the function for Left, Right and Center fanes where selectable. In your application you can select all the functions except this Fanes L+R+3D. Since I use the unit also for heating an automatic wide spread 3-D heat spreak would be a great to have function.

Are there any possibilities to add these functions, or is it not possible with the controller used in the current set-up?

I hope if anybody can give me an answer on this please.

Kind regards and thanks already.

**Comment by mikeschenkel** [comment] 2022-11-04 14:39
This is a duplicate of #77

**Closed** 2022-12-21 22:22 UTC
